# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f70ede6c7bec2545fd781d09d8d64143487316e00b778a33c025259593f678b6e3c1245751795120898af057e98121001761087a9d79115ecd74d10cd3099b8

test:
  secret_key_base: b3125a76b7c1bc3c7cbc71c7555a64e2d8f61af2bb86f504a3df91ccd4bcac5734aaadd379f298bd119493407686b4feb1527b02a5b7834425476804ea36d342

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
